CREATE DATABASE HEALTHCAR
USE HEALTHCAR
SELECT * FROM appointments
SELECT * FROM DOCTORS
SELECT * FROM PATIENTS
SELECT * FROM TREATMENTS
SELECT * FROM billing
--- BASIC---
--- LIST ALL PATIENTS AND THEIR CITY
SELECT NAME ,CITY FROM PATIENTS
GROUP BY NAME ,CITY

--- COUNT TOTAL NUMBERS OF PATIENTS REGISTERD IN 2024
SELECT COUNT(NAME) AS COUNT_OF_PATIENTS FROM PATIENTS
WHERE EXTRACT(YEAR FROM registration_date)='2024'

--- RETRIEVE ALL COMPLETED APPOINTMENTS
SELECT * FROM appointments
WHERE STATUS='Completed'

---FIND ALL UNIQUE DEPARTMENT AVAILABLES
SELECT DISTINCT(DEPARTMENT) FROM doctors

---COUNT HOW MANY DOCTORS WORK IN EACH DEPARTMENT
SELECT DEPARTMENT ,COUNT(NAME) AS DOCTORS FROM doctors
GROUP BY DEPARTMENT

--- FIND ALL APPOINTMENT THAT WERE CANCELED
SELECT * FROM appointments
WHERE status='Cancelled'

--- SHOW THE AVERAGE CONSULTATION FEE PER DEPARTMENT
SELECT department ,SUM(consultation_fee)/COUNT(name) AS AVG_FEE FROM doctors
GROUP BY department

---SHOW COUNT OF DOCTORS AND TOTAL FEE FOR EACH DEPARTMENT
SELECT department , COUNT(name) ,SUM(consultation_fee) AS TOTAL_FEE FROM doctors
GROUP BY department


--- INTERMEDIATE ---

---FIND THE TOP 5 DOCTORS BY NUMEBR OF APPOINTMENTS
SELECT NAME,COUNT(NAME) AS APP FROM doctors
INNER JOIN appointments ON doctors.doctor_id=appointments.doctor_id
GROUP BY NAME ORDER BY APP DESC LIMIT 5

--- CALCULATE TOTAL REVENUE GENERATED BY EACH DOCTOR

SELECT NAME , SUM(consultation_fee) AS TOTAL_REVENUE FROM doctors
INNER JOIN appointments ON doctors.doctor_id=appointments.doctor_id
GROUP BY NAME ORDER BY TOTAL_REVENUE DESC


--- SHOW THE NUMBER OF PATIENTS TREADET BY EACH DOCTOR

SELECT doctors.NAME,COUNT(patients.NAME) COUNT_OF_PATIENTS_TRETED FROM doctors
INNER JOIN appointments ON doctors.doctor_id=appointments.doctor_id
INNER JOIN patients ON appointments.patient_id=patients.patient_id
GROUP BY doctors.NAME ORDER BY COUNT_OF_PATIENTS_TRETED DESC

--- RETRIVE ALL PATIENTS WHO VISITED MORE THAN 3 TIMES

SELECT NAME,COUNT(NAME) AS COUNT_OF_VISIT FROM patients
INNER JOIN  appointments ON patients.patient_id=appointments.patient_id
GROUP BY NAME 
HAVING COUNT_OF_VISIT > 3
ORDER BY COUNT_OF_VISIT DESC


--- FIND THE MOST COMMON DIAGANOSIS AMONG PAITENTS.

SELECT diagnosis ,COUNT(diagnosis) AS COUNT_OF_diagnosis FROM patients
INNER JOIN  appointments ON patients.patient_id=appointments.patient_id
GROUP BY diagnosis ORDER BY COUNT_OF_diagnosis DESC LIMIT 5

--- GET MONTHLY TOTAL REVENUE FROM TREATMENT 

SELECT  MONTHNAME(STR_TO_DATE(appointment_date, '%d-%m-%Y')) AS month ,SUM(cost) AS REVENUE FROM appointments
RIGHT JOIN treatments ON appointments.appointment_id=treatments.appointment_id
GROUP BY MONTH

---LIST ALL PATIENTS WHO HAVE UNPAID BILLS

SELECT patients.name FROM patients
INNER JOIN appointments ON patients.patient_id=appointments.patient_id
INNER JOIN billing ON appointments.appointment_id=billing.appointment_id
WHERE payment_status='Pending'

---FIND DOCTORS WHOSE AVG TREATMENT COST > 10000

SELECT doctors.name,COUNT(doctors.name) AS NUMBER_OF_TREATMENT,SUM(treatments.cost) AS TOTAL_REVENUE, SUM(treatments.cost)/COUNT(doctors.name) AS AVG_TREATMENT_COST FROM treatments
INNER JOIN appointments ON appointments.appointment_id=treatments.appointment_id
INNER JOIN doctors ON doctors.doctor_id=appointments.doctor_id
GROUP BY doctors.name
HAVING AVG_TREATMENT_COST >10000
ORDER BY AVG_TREATMENT_COST DESC



---ADVANCED---
---RANK DOCTORS BY TOTAL REVENUE USING RANK()
SELECT doctors.name,SUM(treatments.cost) AS TOTAL_REVENUE, RANK () OVER(ORDER BY SUM(treatments.cost) DESC ) AS RANK_BY_REVENUE FROM treatments
INNER JOIN appointments ON appointments.appointment_id=treatments.appointment_id
INNER JOIN doctors ON doctors.doctor_id=appointments.doctor_id
GROUP BY doctors.name

--- CALCULATE AVG TREATMENT COST PER DIAGNOSIS AND RANK THEM
SELECT diagnosis,SUM(treatments.cost) AS TOTAL_REVENUE , COUNT(treatments.treatment_id) AS TOTAL_TREATMEN ,SUM(treatments.cost)/COUNT(treatments.treatment_id) AS AVG_COST,
RANK() OVER(ORDER BY SUM(treatments.cost)/COUNT(treatments.cost) )AS COST_RANK FROM treatments
INNER JOIN appointments ON appointments.appointment_id=treatments.appointment_id
GROUP BY diagnosis

---COMPUTE DOCTOR PERFORMANCE SCORE
SELECT doctors.name ,COUNT(treatments.treatment_id) AS TOTAL_TRATMENTS ,SUM(treatments.cost)/COUNT(treatments.treatment_id)AS AVG_COST,SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END)AS CANCELLATIONS FROM treatments
INNER JOIN appointments ON appointments.appointment_id=treatments.appointment_id
INNER JOIN doctors ON doctors.doctor_id=appointments.doctor_id
GROUP BY doctors.name

---FIND TOP 2 MOST PROFITABLE DEPARTMENTS 
SELECT doctors.department,SUM(billing.total_amount)AS REVENUE ,RANK () OVER(ORDER BY SUM(billing.total_amount)) AS REVENUE_RANK FROM appointments 
INNER JOIN doctors ON doctors.doctor_id=appointments.doctor_id
INNER JOIN billing ON billing.appointment_id=appointments.appointment_id
GROUP BY doctors.department
LIMIT 2

